clear all;

data_path = '/data/biophys/yusipov/mbl_zero_super_vector/results';
figures_path = '/home/yusipov/mbl_zero_super_vector/figures';

Nc                  = 8;
dissipator_type     = 1;
alpha               = 0;
energy_type         = 0;
border_conditions   = 1;
W                   = 8;
U                   = 1;
J                   = 1;
g                   = 0.1;
seed_start          = 1;
seed_num            = 100;

num_seed_start = 10;

size_total = seed_num * num_seed_start;

alpha_start = 0.0;
alpha_shift = pi/10.0;
alpha_num = 11;

alphas = zeros(alpha_num, 1);
data = zeros(alpha_num, 1);
alpha_id = 0;

for alpha = alpha_start : alpha_shift : alpha_start + alpha_shift * (alpha_num-1)
    
    alpha_id = alpha_id + 1;
    alpha = alpha
    alphas(alpha_id) = alpha;
    
    avg_data = 0;
    
    for ss = seed_start : seed_num: seed_start + seed_num * (num_seed_start - 1)
       
        for seed = ss : ss + (seed_num-1)
            
            file_name_tree = sprintf('Nc_%d/dt_%d/alpha_%0.4f/et_%d/bc_%d/W_%0.4f/U_%0.4f/J_%0.4f/g_%0.4f/seed_start_%d', ...
                Nc, ...
                dissipator_type, ...
                alpha, ...
                energy_type, ...
                border_conditions, ...
                W, ...
                U, ...
                J, ...
                g, ...
                ss);
            
            file_name_suffix = sprintf('Nc(%d)_dt(%d)_alpha(%0.4f)_et(%d)_bc(%d)_W(%0.4f)_U(%0.4f)_J(%0.4f)_gamma(%0.4f)_ss(%d)_sn(%d)_seed(%d)', ...
                Nc, ...
                dissipator_type, ...
                alpha, ...
                energy_type, ...
                border_conditions, ...
                W, ...
                U, ...
                J, ...
                g, ...
                ss, ...
                seed_num, ...
                seed);
            
            file_name = sprintf('%s/%s/characteristics_%s.txt.txt', ...
                data_path, file_name_tree, file_name_suffix);
            
            local_data = importdata(file_name);
            
            avg_data = avg_data + abs(local_data(1));
        end
    end
    
    avg_data = avg_data / size_total;
    
    data(alpha_id) = avg_data;
    
end

file_name_suffix = sprintf('Nc(%d)_dt(%d)_alpha(var)_et(%d)_bc(%d)_W(%0.4f)_U(%0.4f)_J(%0.4f)_gamma(%0.4f)_sn(%d)', ...
    Nc, ...
    dissipator_type, ...
    energy_type, ...
    border_conditions, ...
    W, ...
    U, ...
    J, ...
    g, ...
    size_total);

figure;
hLine = plot(alphas, data, 'LineWidth', 2);
set(gca, 'FontSize', 30);
xlabel('$\alpha$', 'Interpreter', 'latex');
set(gca, 'FontSize', 30);
ylabel('$<S>$', 'Interpreter', 'latex');

savefig(sprintf('%s/evolution_avg_entropy_from_alpha_%s.fig', ...
    figures_path, file_name_suffix));